export const books = [
  { title: "Things Fall Apart", author: "Chinua Achebe" },
  { title: "Half of a Yellow Sun", author: "Chimamanda Ngozi Adichie" },
  { title: "Season of Migration to the North", author: "Tayeb Salih" },
  { title: "So Long a Letter", author: "Mariama Bâ" },
  { title: "The Beautyful Ones Are Not Yet Born", author: "Ayi Kwei Armah" },
  { title: "We Need New Names", author: "NoViolet Bulawayo" },
  { title: "Nervous Conditions", author: "Tsitsi Dangarembga" },
  { title: "A Grain of Wheat", author: "Ngũgĩ wa Thiong'o" },
  { title: "Cry, the Beloved Country", author: "Alan Paton" },
  { title: "Homegoing", author: "Yaa Gyasi" },
  { title: "Purple Hibiscus", author: "Chimamanda Ngozi Adichie" },
  { title: "The Famished Road", author: "Ben Okri" },
  { title: "Americanah", author: "Chimamanda Ngozi Adichie" },
  { title: "Petals of Blood", author: "Ngũgĩ wa Thiong'o" },
  { title: "The Fishermen", author: "Chigozie Obioma" },
  { title: "The Secret Lives of Baba Segi’s Wives", author: "Lola Shoneyin" },
  { title: "Arrow of God", author: "Chinua Achebe" },
];
